MusicShop/urls.py
from django.contrib import admin
from django.urls import path
from szalonebembeny.views import LandingPageView, ProductsView, CategoriesView, ProductsInCategory, ProductAdd, \
    CategoryAdd, ProductModify, CategoryModify, ProductDelete, CategoryDelete, LoginView, LogoutView, RegisterView, \
    ResetPasswordView, ProductDetailsView, CartView, CommentAddView, CommentEditView, ProductDeleteFromCartView, \
    ProfileEditView, OrderAddView, OrdersView, OrderDetailsView, LikedProductsView, SearchResultsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='main'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('products/', ProductsView.as_view(), name='products'),
    path('categories/', CategoriesView.as_view(), name='categories'),
    path('productscategory/<int:id>/', ProductsInCategory.as_view(), name='category-products'),
    path('product_add/', ProductAdd.as_view(), name='product-add'),
    path('category_add/', CategoryAdd.as_view(), name='category-add'),
    path('product/<slug>/edit/', ProductModify.as_view(), name='product-edit'),
    path('category/<int:pk>/edit/', CategoryModify.as_view(), name='category-edit'),
    path('product/<slug>/delete/', ProductDelete.as_view(), name='product-delete'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category-delete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('reset_password/', ResetPasswordView.as_view(), name='reset-password'),
    path('profile_edit/', ProfileEditView.as_view(), name='profile-edit'),
    path('product/<slug>/', ProductDetailsView.as_view(), name='product'),
    path('comment_add/<slug>', CommentAddView.as_view(), name='comment-add'),
    path('comment_edit/<slug>', CommentEditView.as_view(), name='comment-edit'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/<slug>/delete', ProductDeleteFromCartView.as_view(), name='cart-product-delete'),
    path('order_add/', OrderAddView.as_view(), name='order_add'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order/<int:id>/', OrderDetailsView.as_view(), name='order'),
    path('liked_products/', LikedProductsView.as_view(), name='liked_products')
]

szalonebembeny/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name='Nazwa')
    description = models.TextField(verbose_name='Opis')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Nazwa')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Opis')
    description = models.TextField(verbose_name='Opis')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategoria')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='cena')
    stock = models.IntegerField(verbose_name='Ilość')
    votes = models.IntegerField(default=0, verbose_name='głosy')
    score = models.DecimalField(max_digits=3, decimal_places=1, default=-1, verbose_name='Ocena')
    imgpath = models.CharField(max_length=64, default='Brak zdjęcia')

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=9)
    address = models.CharField(max_length=128)
    liked_products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return f'Profil {self.user.username}'


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    score = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return f'Komentarz {self.user.username} dla produktu {self.product.name}'


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')

    def __str__(self):
        return f'Koszyk {self.user.username}'


class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField()

    def __str__(self):
        return f'{self.amount} {self.product.name} w koszyku {self.cart.user.username}'


STATES = {
    (1, 'Zamówione'),
    (2, 'Opłacone'),
    (3, 'Wysłane'),
    (4, 'Odebrane')
}

DELIVER_METHODS = {
    ('paczkomat', 'Paczkomat Inpost'),
    ('poczta', 'Poczta Polska'),
    ('DPD', 'Kurier DPD')
}

PAYMENT_METHODS = {
    ('przelew', 'Przelew internetowy'),
    ('pobranie', 'Za pobraniem'),
    ('BLIK', 'Płatność BLIK')
}


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='OrderProducts')
    date = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=STATES, default=1)
    address = models.CharField(max_length=128)
    deliver_method = models.CharField(choices=DELIVER_METHODS, max_length=32)
    payment_method = models.CharField(choices=PAYMENT_METHODS, max_length=32)
    full_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Zamówienie {self.user.username} z {self.date}'


class OrderProducts(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField()

    def __str__(self):
        return f'{self.amount} {self.product.name} w zamówieniu {self.order.user.username} z dnia {self.order.date}'

templates/base.html
<!DOCTYPE html>
{% load static %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body style="background-image: url('{% static 'img/background2.jpg' %}')" >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main' %}">Music Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'categories' %}">Kategorie</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products' %}">Produkty</a>
        </li>
      </ul>
      <form class="d-flex" method="post" action="{% url 'search' %}">
          {% csrf_token %}
        <input name="search" class="form-control me-2" type="search" placeholder="Wyszukaj produkt lub kategorię" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Wyszukaj</button>
      </form>
    </div>
  </div>
</nav>
<div class="p-2" style="background-color: white">
    {% if user.is_authenticated %}
        Zalogowany jako {{ user }}
        <a class="btn btn-secondary btn-sm mx-1" href="{% url 'cart' %}">Twój koszyk</a>
        <a class="btn btn-success btn-sm mx-1" href="{% url 'orders' %}">Twoje zamówienia</a>
        <a class="btn btn-dark btn-sm mx-1" href="{% url 'liked_products' %}">Polubione produkty</a>
        <a class="btn btn-danger btn-sm mx-1 float-end" href="{% url 'logout' %}">Wyloguj</a>
        <a class="btn btn-warning btn-sm mx-1 float-end" href="{% url 'reset-password' %}">Zmiana hasła</a>
        <a class="btn btn-info btn-sm mx-1 float-end" href="{% url 'profile-edit' %}">Edytuj profil</a>
    {% else %}
        <a class="btn btn-success mx-1" href="{% url 'login' %}">Zaloguj</a>
        <a class="btn btn-warning mx-1" href="{% url 'register' %}">Rejestruj</a>
    {% endif %}
</div>

{% block content %}
{% endblock %}

<script>
    setTimeout(function () {
        let monit = document.getElementById('msg');
        if (monit) {
            monit.remove();
        }
    }, 2000)
</script>

</body>
</html>

templates/basic_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="container d-flex align-content-center w-auto" style="background-color: white; margin: 50px; padding: 10px">
    <div class="d-flex align-items-center flex-column">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="{{ button }}">
    </form>
    </div>
    </div>
    <div class="container">
            {% include 'messages.html' %}
    </div>
{% endblock %}

templates/cart.html
{% extends "base.html" %}

{% block title %}
    Twój koszyk
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Twój koszyk{{ emptycart }}</h2>
    </div>
    {% if emptycart == '' %}
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Nazwa produktu</th>
        <th scope="col">Cena</th>
        <th scope="col">Ilość</th>
        <th scope="col">Łączna kwota</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for product in cart.products.all|dictsort:'name' %}
        <tr>
            <td><a href="{% url 'product' slug=product.slug %}">{{ product.name }}</a></td>
            <td>{{ product.price }} zł</td>
            {% for cartproduct in product.cartproducts_set.all %}
                {% if cartproduct.cart.user == user %}
                    <td>
                    <form method="post">
                        {% csrf_token %}
                        <input name="product_id" type="text" hidden value="{{ product.id }}">
                        <button name="sub" class="btn btn-outline-danger btn-sm" style="border-width: 2px; font-size: 20px; line-height: 25px; width: 40px" type="submit" value="-1">&#8722;</button>
                        {{ cartproduct.amount }}
                        <button name="add" class="btn btn-outline-success btn-sm" style="border-width: 2px; font-size: 20px; line-height: 25px; width: 40px" type="submit" value="+1">&#65291;</button>
                    </form>
                    </td>
                    <td>{% widthratio product.price 1 cartproduct.amount %}.00 zł</td>
                {% endif %}
            {% endfor %}
            <td><a type="button" class="btn btn-danger" href="{% url 'cart-product-delete' slug=product.slug %}">Usuń z koszyka</a></td>
        </tr>
    {% endfor %}
    <tr>
        <td></td><td></td><td></td><td>{% if cart.products.all|length > 1 %}{{ full_cost }} zł{% endif %}</td><td><a type="button" class="btn btn-primary" href="{% url 'order_add' %}">Przejdź do zamówienia</a> </td>
    </tr>
    </table>
        <div class="container d-flex justify-content-center">
            {% include 'messages.html' %}
        </div>
    {% endif %}
{% endblock %}

templates/categories.html
{% extends "base.html" %}

{% block title %}
    Kategorie
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Kategorie</h2>
    </div>
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Nazwa kategorii</th>
        <th scope="col">Opis</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for category in categories %}
        <tr>
        <td><a href="{% url 'category-products' id=category.id %}">{{ category.name }}</a></td>
        <td>{{ category.description }}</td>
        {% if perms.szalonebembeny.change_category %}
        <td><a type="button" class="btn btn-warning" href="{% url 'category-edit' pk=category.id %}">Edytuj</a></td>
        {% endif %}
        {% if perms.szalonebembeny.delete_category %}
        <td><a type="button" class="btn btn-danger" href="{% url 'category-delete' pk=category.id %}">Usuń</a></td>
        {% endif %}
        </tr>
    {% endfor %}
    {% if perms.szalonebembeny.add_category %}
        <tr>
            <td><a type="button" class="btn btn-primary" href="{% url 'category-add' %}">Dodaj Kategorię</a></td>
        </tr>
    {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
    Music Shop
{% endblock %}

{% block content %}
<table class="table container my-4" style="background-color: white">
    <tr>
        <th>Najlepiej ocenianie produkty:</th>
        <th>Ocena:</th>
    </tr>
    {% for product in products %}
    <tr>
        <td><a href="{% url 'product' slug=product.slug %}">{{ product.name }}</a></td>
        <td>{{ product.score }}</td>
    </tr>
    {% endfor %}
</table>
<div class="container-fluid bg-light p-2 mt-lg-5">
    <div class="row p-2">
        <div class="col p-2">
            <h4>O nas</h4>
            <p>Jesteśmy sklepem sprzedającym instrumenty, sprzęt i akcesoria muzyczne. Działamy od 2012 roku. Prowadzimy nasz sklep z pasją i ogromnym zaangażowaniem.</p>
        </div>
        <div class="col">
            <h4>Kontakt</h4>
            <ul>
                <li>Adres: Muzyczna 15 00-005 Warszawa</li>
                <li>Numer telefonu: 782-584-232</li>
                <li>Adres E-mail: sklep@musicshop.pl</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2 align-content-center float-none" style="width: 200px" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/order-details.html
{% extends "base.html" %}

{% block title %}
    Szczegóły zamówienia {{ order.id }}
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Zamówienie {{ order.id }}</h2>
    </div>
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Nazwa produktu</th>
        <th scope="col">Cena</th>
        <th scope="col">Ilość</th>
        <th scope="col">Łączna kwota</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for product in order.products.all %}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.price }} zł</td>
            {% for orderproduct in product.orderproducts_set.all %}
                {% if orderproduct.order.user == user and orderproduct.order == order %}
                    <td>{{ orderproduct.amount }}</td>
                    <td>{% widthratio product.price 1 orderproduct.amount %}.00 zł</td>
                {% endif %}
            {% endfor %}
        </tr>
    {% endfor %}
    <tr>
        <td></td><td></td><td></td><td>{{ order.full_price }} zł</td>
    </tr>
    </table>
    <div class="container p-2 my-4" style="background-color: white">
    <table class="table">
        <tr><td>Data złożenia zamówienia</td><td>{{ order.date }}</td></tr>
        <tr><td>Status zamówienia</td><td>{{ order.get_state_display }}</td></tr>
        <tr><td>Sposób dostawy</td><td>{{ order.get_deliver_method_display }}</td></tr>
        <tr><td>Adres dostawy</td><td>{{ order.address }}</td></tr>
        <tr><td>Metoda płatności</td><td>{{ order.get_payment_method_display }}</td></tr>
    </table>
    </div>
{% endblock %}

templates/order_form.html
{% extends "base.html" %}

{% block title %}
    Składanie zamówienia
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Podsumowanie zamówienia</h2>
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Nazwa produktu</th>
        <th scope="col">Cena</th>
        <th scope="col">Ilość</th>
        <th scope="col">Łączna kwota</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for product in cart.products.all %}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.price }} zł</td>
            {% for cartproduct in product.cartproducts_set.all %}
                {% if cartproduct.cart.user == user %}
                    <td>{{ cartproduct.amount }}</td>
                    <td>{% widthratio product.price 1 cartproduct.amount %}.00 zł</td>
                {% endif %}
            {% endfor %}
        </tr>
    {% endfor %}
    {% if cart.products.all|length > 1 %}
    <tr>
        <td></td><td></td><td></td><td>{{ full_cost }} zł</td>
    </tr>
    {% endif %}
    </table>
    <div class="d-flex align-items-center flex-column">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Złóż zamówienie">
        <a href="{% url 'cart' %}" class="btn btn-danger">Wróc do koszyka</a>
    </form>
    </div>
    </div>
{% endblock %}

templates/orders.html
{% extends "base.html" %}

{% block title %}
    Twoje zamówienia
{% endblock %}

{% block content %}
    {% if orders|length > 0 %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Twoje zamówienia</h2>
    </div>
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Zamówienie</th>
        <th scope="col">Data złożenia zamówienia</th>
        <th scope="col">Status zamówienia</th>
        <th scope="col">Sposób dostawy</th>
        <th scope="col">Adres dostawy</th>
        <th scope="col">Metoda płatności</th>
        <th scope="col">Kwota zamówienia</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.date }}</td>
            <td>{{ order.get_state_display }}</td>
            <td>{{ order.get_deliver_method_display }}</td>
            <td>{{ order.address }}</td>
            <td>{{ order.get_payment_method_display }}</td>
            <td>{{ order.full_price }} zł</td>
            <td><a class="btn btn-primary" href="{% url 'order' id=order.id %}">Szczegóły</a></td>
        </tr>
    {% endfor %}
    </table>
    {% else %}
        <div class="container p-2 my-4" style="background-color: white">
            <h2>Nie masz jeszcze zamówień</h2>
        </div>
    {% endif %}
{% endblock %}

templates/product-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
    <div class="container my-4" style="background-color: white">
        <div class="row">
            <div class="col">
                <img src="{% static product.imgpath|safe %}" alt="Brak zdjęć">
            </div>
            <div class="col position-relative">
                <ul class="list-unstyled p-3">
                    <li class="h4 p-1">{{ product.name }}</li>
                    <li class="p-1">{{ product.description }}</li>
                    <li class="p-1">Kategoria: {{ product.category }}</li>
                    <li class="p-1">Cena: {{ product.price }} zł</li>
                    <li class="p-1">Ilość polubień: {{ product.votes }}</li>
                    <li class="p-1">{% if product.score < 0 %}Brak ocen{% else %}Średnia ocena: {{ product.score }}{% endif %}</li>
                    <li class="p-1" style="color: {% if product.stock > 0 %}green">Dostępny{% else %}red">Niedostępny{% endif %}</li>
                </ul>
                {% if user.is_authenticated %}
                <form method="POST">
                    {% csrf_token %}
                    {% if not product_in_like %}
                        <button class="btn btn-success" style="width: 170px" type="submit" value="like" name="like">Polub</button>
                    {% else %}
                        <button class="btn btn-danger" style="width: 170px" type="submit" value="unlike" name="unlike">Usuń z polubionych</button>
                    {% endif %}
                    {% if product.stock > 0 %}
                    <button class="btn btn-primary" style="width: 170px" type="submit" value="cart" name="cart">Dodaj do koszyka</button>
                        <div class="d-flex justify-content-center">
                        {% include 'messages.html' %}
                        </div>
                    {% endif %}
                </form>
                {% else %}
                    <button type="button" class="btn btn-success w-auto" disabled>Zaloguj się, aby polubić</button>
                    <button type="button" class="btn btn-primary w-auto" disabled>Zaloguj się, aby dodać do koszyka</button>
                {% endif %}
            </div>
        </div>
        <div class="row p-2">
            <h2>Komentarze</h2>
            {% for comment in comments %}
                <div class="card mb-1">
                    <h4 class="card-title">{{ comment.user.username }}</h4>
                    <p class="card-subtitle">{{ comment.date }}</p>
                    <h6 class="card-text">{{ comment.content }}</h6>
                    <p class="card-text">Ocena: {{ comment.score }}</p>
                </div>
            {% endfor %}
        {% if user.is_authenticated %}
            {% if comment_added %}
                <a class="btn btn-primary w-auto" href="{% url 'comment-edit' slug=product.slug %}">Edytuj komentarz</a>
            {% else %}
                <a class="btn btn-primary w-auto" href="{% url 'comment-add' slug=product.slug %}">Dodaj komentarz</a>
            {% endif %}
        {% else %}
            <button type="button" class="btn btn-primary w-auto" disabled>Zaloguj się, aby dodać komentarz</button>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>{{ title }}</h2>
    </div>
    <table class="table container my-4" style="background-color: white">
    <thead>
    <tr class= "text-color-darker">
        <th scope="col">Nazwa produktu</th>
        <th scope="col">Opis</th>
        <th scope="col">Kategoria</th>
        <th scope="col">Cena</th>
        <th scope="col">Ocena</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for product in products %}
        <tr>
        <td><a href="{% url 'product' slug=product.slug %}">{{ product.name }}</a></td>
        <td>{{ product.description }}</td>
        <td>
            {% if title == 'Wszystkie produkty' %}
            <a href="{% url 'category-products' id=product.category.id %}">{{ product.category }}</a>
            {% else %}
            {{ product.category }}
            {% endif %}
        </td>
        <td class="col-1">{{ product.price }} zł</td>
        <td class="col-1">{% if product.score < 0 %}Brak ocen{% else %}{{ product.score }}{% endif %}</td>
        {% if perms.szalonebembeny.change_product %}
        <td class="col-1"><a type="button" class="btn btn-warning" href="{% url 'product-edit' slug=product.slug %}">Edytuj</a></td>
        {% endif %}
        {% if perms.szalonebembeny.delete_product %}
        <td><a type="button" class="btn btn-danger" href="{% url 'product-delete' slug=product.slug %}">Usuń</a></td>
        {% endif %}
        </tr>
    {% endfor %}
    {% if perms.szalonebembeny.add_product %}
        <tr>
            <td><a type="button" class="btn btn-primary" href="{% url 'product-add' %}">Dodaj Produkt</a></td>
        </tr>
    {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/search_results.html
{% extends "base.html" %}

{% block title %}
    Wyniki wyszukiwania
{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Wyniki wyszukiwania</h2>
    </div>
    <table class="table container my-4" style="background-color: white">
    <thead>
    {% if categories|length > 0 %}
    <tr class= "text-color-darker">
        <th scope="col">Nazwa kategorii</th>
        <th scope="col">Opis</th>
    </tr>
    </thead>
    <tbody class="text-color-lighter">
    {% for category in categories %}
        <tr>
        <td><a href="{% url 'category-products' id=category.id %}">{{ category.name }}</a></td>
        <td>{{ category.description }}</td>
        {% if perms.szalonebembeny.change_category %}
        <td><a type="button" class="btn btn-warning" href="{% url 'category-edit' pk=category.id %}">Edytuj</a></td>
        {% endif %}
        {% if perms.szalonebembeny.delete_category %}
        <td><a type="button" class="btn btn-danger" href="{% url 'category-delete' pk=category.id %}">Usuń</a></td>
        {% endif %}
        </tr>
    {% endfor %}
    {% else %}
        <tr class= "text-color-darker">
        <th scope="col">Nie znaleziono kategorii</th>
    </tr>
    </thead>
    {% endif %}
    <thead>
    {% if products|length > 0 %}
    <tr class= "text-color-darker">
        <th scope="col">Nazwa produktu</th>
        <th scope="col">Opis</th>
        <th scope="col">Kategoria</th>
        <th scope="col">Cena</th>
        <th scope="col">Ocena</th>
    </tr>
    </thead>
    {% for product in products %}
        <tr>
        <td><a href="{% url 'product' slug=product.slug %}">{{ product.name }}</a></td>
        <td>{{ product.description }}</td>
        <td>
            <a href="{% url 'category-products' id=product.category.id %}">{{ product.category }}</a>
        </td>
        <td class="col-1">{{ product.price }} zł</td>
        <td class="col-1">{% if product.score < 0 %}Brak ocen{% else %}{{ product.score }}{% endif %}</td>
        {% if perms.szalonebembeny.change_product %}
        <td class="col-1"><a type="button" class="btn btn-warning" href="{% url 'product-edit' slug=product.slug %}">Edytuj</a></td>
        {% endif %}
        {% if perms.szalonebembeny.delete_product %}
        <td><a type="button" class="btn btn-danger" href="{% url 'product-delete' slug=product.slug %}">Usuń</a></td>
        {% endif %}
        </tr>
    {% endfor %}
    {% else %}
        <tr class= "text-color-darker">
        <th scope="col">Nie znaleziono produktów</th>
    </tr>
    </thead>
    {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/thank_you.html
{% extends 'base.html' %}

{% block title %}Złożyłeś zamówienie{% endblock %}

{% block content %}
    <div class="container p-2 my-4" style="background-color: white">
    <h2>Dziękujemy za złożenie zamówienia!</h2>
    </div>
{% endblock %}